### ISSUE TITLE
Respawn error

### ISSUE THREAD

**Issue by MCPEPluginer16** [Bluplayz/BedwarsPE#15]
I have error when player is getroben not spawned on the BedWars arena

**Comment by Driesboy** [comment]
reset the spawns /bw setspawn (arena) (team)

**Comment by MCPEPluginer16** [comment]
Dont Work

**Comment by MCPEPluginer16** [comment]
I installed 26 Plugins :D

**Comment by Driesboy** [comment]
Thats the problem!
Op 5-jun.-2016 17:09 schreef "MCPEPluginer16" <notifications@github.com>:

**Comment by MCPEPluginer16** [comment]
.-.

**Comment by MCPEPluginer16** [comment]
I installer EssentialsPE but when delete it worked Respawn

**Comment by Driesboy** [comment]
close it than!
