### ISSUE TITLE
Someone stole you're plugin

### ISSUE THREAD

**Issue by KairusDarkSeeker** [Bluplayz/BedwarsPE#25]
[here's](https://github.com/AbelGamerC/BedWars) the plugin stealer

**Comment by SalmonGER** [comment]
Actually the code is pretty different

**Comment by KairusDarkSeeker** [comment]
Nope, its not. He just added the classes on different files

**Comment by IrishPacks** [comment]
If you look with your fucking eyes, you can obviously tell that their code is super different. Please close this invalid issue smh.

**Comment by xZeroMCPE** [comment]
lol *the feeling of being stupid* 

*closed issue* XD
